import BellePlaineRulesCardRanker from '../BellePlaineRulesCardRanker'
import Suit from '../Suit'

describe('Belle Plaine Rules', () => {
  it('Should have the BP Rank', () => {
    expect(new BellePlaineRulesCardRanker().getRank('qc')).toBe(1)
    expect(new BellePlaineRulesCardRanker().getRank('7d')).toBe(2)
    expect(new BellePlaineRulesCardRanker().getRank('qs')).toBe(3)
    expect(new BellePlaineRulesCardRanker().getRank('qh')).toBe(4)
    expect(new BellePlaineRulesCardRanker().getRank('qd')).toBe(5)
    expect(new BellePlaineRulesCardRanker().getRank('jc')).toBe(6)
    expect(new BellePlaineRulesCardRanker().getRank('js')).toBe(7)
    expect(new BellePlaineRulesCardRanker().getRank('jh')).toBe(8)
    expect(new BellePlaineRulesCardRanker().getRank('jd')).toBe(9)
    expect(new BellePlaineRulesCardRanker().getRank('ad')).toBe(10)
    expect(new BellePlaineRulesCardRanker().getRank('td')).toBe(11)
    expect(new BellePlaineRulesCardRanker().getRank('kd')).toBe(12)
    expect(new BellePlaineRulesCardRanker().getRank('9d')).toBe(13)
    expect(new BellePlaineRulesCardRanker().getRank('8d')).toBe(14)
    expect(new BellePlaineRulesCardRanker().getRank('ac')).toBe(15)
    expect(new BellePlaineRulesCardRanker().getRank('as')).toBe(16)
    expect(new BellePlaineRulesCardRanker().getRank('ah')).toBe(17)
    expect(new BellePlaineRulesCardRanker().getRank('tc')).toBe(18)
    expect(new BellePlaineRulesCardRanker().getRank('ts')).toBe(19)
    expect(new BellePlaineRulesCardRanker().getRank('th')).toBe(20)
    expect(new BellePlaineRulesCardRanker().getRank('kc')).toBe(21)
    expect(new BellePlaineRulesCardRanker().getRank('ks')).toBe(22)
    expect(new BellePlaineRulesCardRanker().getRank('kh')).toBe(23)
    expect(new BellePlaineRulesCardRanker().getRank('9c')).toBe(24)
    expect(new BellePlaineRulesCardRanker().getRank('9s')).toBe(25)
    expect(new BellePlaineRulesCardRanker().getRank('9h')).toBe(26)
  })
  it('Should have the standard points', () => {
    expect(new BellePlaineRulesCardRanker().getPointValue('ad')).toBe(11)
    expect(new BellePlaineRulesCardRanker().getPointValue('ac')).toBe(11)
    expect(new BellePlaineRulesCardRanker().getPointValue('as')).toBe(11)
    expect(new BellePlaineRulesCardRanker().getPointValue('ah')).toBe(11)

    expect(new BellePlaineRulesCardRanker().getPointValue('td')).toBe(10)
    expect(new BellePlaineRulesCardRanker().getPointValue('tc')).toBe(10)
    expect(new BellePlaineRulesCardRanker().getPointValue('ts')).toBe(10)
    expect(new BellePlaineRulesCardRanker().getPointValue('th')).toBe(10)

    expect(new BellePlaineRulesCardRanker().getPointValue('kd')).toBe(4)
    expect(new BellePlaineRulesCardRanker().getPointValue('kc')).toBe(4)
    expect(new BellePlaineRulesCardRanker().getPointValue('ks')).toBe(4)
    expect(new BellePlaineRulesCardRanker().getPointValue('kh')).toBe(4)

    expect(new BellePlaineRulesCardRanker().getPointValue('qc')).toBe(3)
    expect(new BellePlaineRulesCardRanker().getPointValue('qs')).toBe(3)
    expect(new BellePlaineRulesCardRanker().getPointValue('qh')).toBe(3)
    expect(new BellePlaineRulesCardRanker().getPointValue('qd')).toBe(3)

    expect(new BellePlaineRulesCardRanker().getPointValue('jc')).toBe(2)
    expect(new BellePlaineRulesCardRanker().getPointValue('js')).toBe(2)
    expect(new BellePlaineRulesCardRanker().getPointValue('jh')).toBe(2)
    expect(new BellePlaineRulesCardRanker().getPointValue('jd')).toBe(2)

    expect(new BellePlaineRulesCardRanker().getPointValue('7d')).toBe(0)
    expect(new BellePlaineRulesCardRanker().getPointValue('9c')).toBe(0)
    expect(new BellePlaineRulesCardRanker().getPointValue('9d')).toBe(0)
    expect(new BellePlaineRulesCardRanker().getPointValue('8d')).toBe(0)
    expect(new BellePlaineRulesCardRanker().getPointValue('9s')).toBe(0)
    expect(new BellePlaineRulesCardRanker().getPointValue('9h')).toBe(0)
  })

  it('Should have the correct suits', () => {
    expect(new BellePlaineRulesCardRanker().getSuit('7d')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('qd')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('jd')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('ad')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('td')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('kd')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('9d')).toBe(Suit.DIAMOND)
    expect(new BellePlaineRulesCardRanker().getSuit('8d')).toBe(Suit.DIAMOND)

    expect(new BellePlaineRulesCardRanker().getSuit('qc')).toBe(Suit.CLUB)
    expect(new BellePlaineRulesCardRanker().getSuit('ac')).toBe(Suit.CLUB)
    expect(new BellePlaineRulesCardRanker().getSuit('tc')).toBe(Suit.CLUB)
    expect(new BellePlaineRulesCardRanker().getSuit('kc')).toBe(Suit.CLUB)
    expect(new BellePlaineRulesCardRanker().getSuit('9c')).toBe(Suit.CLUB)
    expect(new BellePlaineRulesCardRanker().getSuit('jc')).toBe(Suit.CLUB)

    expect(new BellePlaineRulesCardRanker().getSuit('as')).toBe(Suit.SPADE)
    expect(new BellePlaineRulesCardRanker().getSuit('qs')).toBe(Suit.SPADE)
    expect(new BellePlaineRulesCardRanker().getSuit('ts')).toBe(Suit.SPADE)
    expect(new BellePlaineRulesCardRanker().getSuit('ks')).toBe(Suit.SPADE)
    expect(new BellePlaineRulesCardRanker().getSuit('js')).toBe(Suit.SPADE)
    expect(new BellePlaineRulesCardRanker().getSuit('9s')).toBe(Suit.SPADE)

    expect(new BellePlaineRulesCardRanker().getSuit('ah')).toBe(Suit.HEART)
    expect(new BellePlaineRulesCardRanker().getSuit('qh')).toBe(Suit.HEART)
    expect(new BellePlaineRulesCardRanker().getSuit('th')).toBe(Suit.HEART)
    expect(new BellePlaineRulesCardRanker().getSuit('jh')).toBe(Suit.HEART)
    expect(new BellePlaineRulesCardRanker().getSuit('kh')).toBe(Suit.HEART)
    expect(new BellePlaineRulesCardRanker().getSuit('9h')).toBe(Suit.HEART)
  })

  it('Should have correct trump indication for each card', () => {
    expect(new BellePlaineRulesCardRanker().isTrump('qc')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('7d')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('qs')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('qh')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('qd')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('jc')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('js')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('jh')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('jd')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('ad')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('td')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('kd')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('9d')).toBe(true)
    expect(new BellePlaineRulesCardRanker().isTrump('8d')).toBe(true)

    expect(new BellePlaineRulesCardRanker().isTrump('ac')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('tc')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('kc')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('9c')).toBe(false)

    expect(new BellePlaineRulesCardRanker().isTrump('as')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('ts')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('ks')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('9s')).toBe(false)

    expect(new BellePlaineRulesCardRanker().isTrump('ah')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('th')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('kh')).toBe(false)
    expect(new BellePlaineRulesCardRanker().isTrump('9h')).toBe(false)
  })
  it('Should return all cardIds correctly', () => {
    expect(new BellePlaineRulesCardRanker().getAllCardIds().length).toBe(26)
  })
})
